# Generated by Django 5.0 on 2024-01-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lecture", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="thumbnail",
            field=models.ImageField(
                default="default_thumbnail.jpg", upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.FileField(null=True, upload_to="videos/", verbose_name=""),
        ),
    ]
